export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  INITIAL_X: "INITIAL_X",
  PER_PAGE: "PER_PAGE",
  SET_SORT: "SET_SORT",
  SET_ACTIVE: "SET_ACTIVE",
  PAGE_COUNT: "PAGE_COUNT",
  ARRAY_LENGTH: "ARRAY_lENGTH",
  SET_DATA: "SET_DATA",
  SET_CART_ITEM: "SET_CART_ITEM",
  SET_IS_SET: "SET_IS_SET",
};
